version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - kafka-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  email-ms:
    build:
      context: ./email-ms
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8778:8778
    networks:
      - kafka-network
    depends_on:
      - kafka
  iam-ms:
    build:
      context: ./iam-ms
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8668:8668
    networks:
      - kafka-network
    depends_on:
      - kafka
  order-ms:
    build:
      context: ./order-ms
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8143:8143
    networks:
      - kafka-network
    depends_on:
      - kafka
  stock-ms:
    build:
      context: ./stock-ms
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8889:8889
    networks:
      - kafka-network
    depends_on:
      - kafka

  account-ms:
    build:
      context: ./account-ms
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8243:8243
    networks:
      - kafka-network
    depends_on:
      - kafka
networks:
  kafka-network:
    driver: bridge